/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Exceptions.GameExeption;
import Exceptions.LoginException;
import Model.Pc;
import gpubattle.DAO.PcDAO;
import gpubattle.DAO.TestDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.Interface;
import gpubattle.DAO.GameDAO;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Home() {

        setResizable(false);
   //     this.setLocationRelativeTo(n);
        initComponents();
        setIcon();
    }
    Login n = new Login();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenu1 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonRun = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        GtaIcon = new javax.swing.JLabel();
        jRadioGta = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        FarCryIcon = new javax.swing.JLabel();
        jRadioButtonFarCry = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        ACOriginsIcon = new javax.swing.JLabel();
        jRadioButtonACOrigins = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaInfoPc1 = new javax.swing.JTextArea();
        warIcon3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableTest1 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPaneGlogalFps1 = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPaneCostPerFrame1 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxPcInfo3 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextAreaInfoPc2 = new javax.swing.JTextArea();
        warIcon4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableTest2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneGlogalFps2 = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPaneCostPerFrame2 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxPcInfo2 = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabel2.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonRun.setText("Run");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        GtaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gta.png"))); // NOI18N
        GtaIcon.setToolTipText("");
        GtaIcon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GtaIconFocusGained(evt);
            }
        });
        GtaIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GtaIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GtaIconMouseExited(evt);
            }
        });
        jPanel2.add(GtaIcon);

        jRadioGta.setText("Gta 5");
        jRadioGta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGtaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioGta);

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        FarCryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/farcry 5.png"))); // NOI18N
        FarCryIcon.setToolTipText("");
        FarCryIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FarCryIconMouseEntered(evt);
            }
        });
        jPanel4.add(FarCryIcon);

        jRadioButtonFarCry.setText("Far Cry 5");
        jRadioButtonFarCry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButtonFarCryFocusGained(evt);
            }
        });
        jRadioButtonFarCry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFarCryActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonFarCry);

        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        ACOriginsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/origins.png"))); // NOI18N
        ACOriginsIcon.setToolTipText("");
        ACOriginsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACOriginsIconMouseEntered(evt);
            }
        });
        jPanel5.add(ACOriginsIcon);

        jRadioButtonACOrigins.setText("A.C. Origins");
        jRadioButtonACOrigins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonACOriginsActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonACOrigins);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO 2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRun, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaInfoPc1.setEditable(false);
        jTextAreaInfoPc1.setColumns(20);
        jTextAreaInfoPc1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaInfoPc1.setForeground(new java.awt.Color(255, 51, 153));
        jTextAreaInfoPc1.setRows(5);
        jScrollPane10.setViewportView(jTextAreaInfoPc1);

        jPanel6.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 379, 200));

        warIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pc1.png"))); // NOI18N
        warIcon3.setToolTipText("");
        warIcon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                warIcon3MouseEntered(evt);
            }
        });
        jPanel6.add(warIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jTableTest1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableTest1.setForeground(new java.awt.Color(255, 51, 153));
        jTableTest1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Games", "1K"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableTest1);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 379, 110));

        jTextPaneGlogalFps1.setEditable(false);
        jTextPaneGlogalFps1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextPaneGlogalFps1.setForeground(new java.awt.Color(255, 51, 153));
        jTextPaneGlogalFps1.setText("00,00");
        jScrollPane8.setViewportView(jTextPaneGlogalFps1);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 75));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 153));
        jLabel17.setText("Global Fps");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTextPaneCostPerFrame1.setEditable(false);
        jTextPaneCostPerFrame1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextPaneCostPerFrame1.setForeground(new java.awt.Color(255, 51, 153));
        jTextPaneCostPerFrame1.setText("00,00");
        jScrollPane11.setViewportView(jTextPaneCostPerFrame1);

        jPanel6.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 75));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 153));
        jLabel14.setText("PC1");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 153));
        jLabel18.setText("Custo / Frame ");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jComboBoxPcInfo3.setForeground(new java.awt.Color(204, 0, 204));
        jComboBoxPcInfo3.setPreferredSize(new java.awt.Dimension(180, 26));
        jComboBoxPcInfo3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxPcInfo3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBoxPcInfo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxPcInfo3MouseEntered(evt);
            }
        });
        jComboBoxPcInfo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPcInfo3ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBoxPcInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaInfoPc2.setEditable(false);
        jTextAreaInfoPc2.setColumns(20);
        jTextAreaInfoPc2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaInfoPc2.setForeground(new java.awt.Color(0, 177, 177));
        jTextAreaInfoPc2.setRows(5);
        jScrollPane12.setViewportView(jTextAreaInfoPc2);

        jPanel7.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 379, 200));

        warIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pc2.png"))); // NOI18N
        warIcon4.setToolTipText("");
        warIcon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                warIcon4MouseEntered(evt);
            }
        });
        jPanel7.add(warIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jTableTest2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableTest2.setForeground(new java.awt.Color(0, 177, 177));
        jTableTest2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Games", "1K"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableTest2);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 379, 110));

        jTextPaneGlogalFps2.setEditable(false);
        jTextPaneGlogalFps2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextPaneGlogalFps2.setForeground(new java.awt.Color(0, 177, 177));
        jTextPaneGlogalFps2.setText("00,00");
        jScrollPane9.setViewportView(jTextPaneGlogalFps2);

        jPanel7.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 75));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 177, 177));
        jLabel19.setText("Global Fps");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTextPaneCostPerFrame2.setEditable(false);
        jTextPaneCostPerFrame2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextPaneCostPerFrame2.setForeground(new java.awt.Color(0, 177, 177));
        jTextPaneCostPerFrame2.setText("00,00");
        jScrollPane13.setViewportView(jTextPaneCostPerFrame2);

        jPanel7.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 75));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 177, 177));
        jLabel15.setText("PC2");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 177, 177));
        jLabel20.setText("Custo / Frame ");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jComboBoxPcInfo2.setForeground(new java.awt.Color(222, 11, 116));
        jComboBoxPcInfo2.setPreferredSize(new java.awt.Dimension(180, 26));
        jComboBoxPcInfo2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxPcInfo2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBoxPcInfo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxPcInfo2MouseEntered(evt);
            }
        });
        jComboBoxPcInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPcInfo2ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBoxPcInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 60, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed

        Interface inter = new Interface();

        inter.cleanTable(jTableTest1); //Limpando a tabela
        inter.cleanTable(jTableTest2); //Limpando a tabela

        //Jogos selecionados
        ArrayList<String> gamesSelected = inter.gamesSelected(jRadioButtonFarCry, jRadioButtonACOrigins, jRadioGta);
        try {
            if (gamesSelected.size() > 0) {
                //Mostra as infos na tela
                inter.setInfoInterface(gamesSelected, jTableTest1, jComboBoxPcInfo3, jTextPaneCostPerFrame1, jTextPaneGlogalFps1, jTextAreaInfoPc1);
                inter.setInfoInterface(gamesSelected, jTableTest2, jComboBoxPcInfo2, jTextPaneCostPerFrame2, jTextPaneGlogalFps2, jTextAreaInfoPc2);
            } else {
                throw new GameExeption("Selecione algum jogo!");
            }
        } catch (GameExeption g1) {
            JOptionPane.showMessageDialog(null, g1.getMsg());
        }

    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jRadioButtonACOriginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonACOriginsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonACOriginsActionPerformed

    private void jRadioGtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioGtaActionPerformed

    private void jRadioButtonFarCryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFarCryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFarCryActionPerformed

    private void GtaIconFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GtaIconFocusGained

    }//GEN-LAST:event_GtaIconFocusGained

    private void jRadioButtonFarCryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButtonFarCryFocusGained

    }//GEN-LAST:event_jRadioButtonFarCryFocusGained

    private void GtaIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtaIconMouseEntered
        
        GameDAO gd = new GameDAO();
        String name = "Gta 5";
        jTextArea1.setText(gd.getInfoGame(name));
    }//GEN-LAST:event_GtaIconMouseEntered

    private void GtaIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtaIconMouseExited


    }//GEN-LAST:event_GtaIconMouseExited

    private void FarCryIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FarCryIconMouseEntered
        
        GameDAO gd = new GameDAO();
        String name = "Far Cry 5";
        jTextArea1.setText(gd.getInfoGame(name));
    }//GEN-LAST:event_FarCryIconMouseEntered

    private void jComboBoxPcInfo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPcInfo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPcInfo3ActionPerformed

    private void jComboBoxPcInfo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxPcInfo3MouseEntered
        
        PcDAO pd = new PcDAO();
        String name = (String) jComboBoxPcInfo3.getSelectedItem();
        jTextArea1.setText(pd.SelectInfoPc(name));
    }//GEN-LAST:event_jComboBoxPcInfo3MouseEntered

    private void jComboBoxPcInfo3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxPcInfo3AncestorAdded
        
        PcDAO pcDAO = new PcDAO();
        ArrayList<Pc> PcList = pcDAO.SelectAllPc();

        jComboBoxPcInfo3.removeAll();

        for (int i = 0; i < PcList.size(); i++) {
            jComboBoxPcInfo3.addItem(PcList.get(i).name);
        }
    }//GEN-LAST:event_jComboBoxPcInfo3AncestorAdded

    private void ACOriginsIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACOriginsIconMouseEntered
        
        GameDAO gd = new GameDAO();
        String name = "Assassin´s creed: Origins";
        jTextArea1.setText(gd.getInfoGame(name));
    }//GEN-LAST:event_ACOriginsIconMouseEntered

    private void warIcon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warIcon3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_warIcon3MouseEntered

    private void warIcon4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warIcon4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_warIcon4MouseEntered

    private void jComboBoxPcInfo2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxPcInfo2AncestorAdded
        
        PcDAO pcDAO = new PcDAO();
        ArrayList<Pc> PcList = pcDAO.SelectAllPc();

        jComboBoxPcInfo2.removeAll();

        for (int i = 0; i < PcList.size(); i++) {
            jComboBoxPcInfo2.addItem(PcList.get(i).name);
        }
    }//GEN-LAST:event_jComboBoxPcInfo2AncestorAdded

    private void jComboBoxPcInfo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxPcInfo2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPcInfo2MouseEntered

    private void jComboBoxPcInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPcInfo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPcInfo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* image test */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACOriginsIcon;
    private javax.swing.JLabel FarCryIcon;
    private javax.swing.JLabel GtaIcon;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JComboBox<String> jComboBoxPcInfo2;
    private javax.swing.JComboBox<String> jComboBoxPcInfo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonACOrigins;
    private javax.swing.JRadioButton jRadioButtonFarCry;
    private javax.swing.JRadioButton jRadioGta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableTest1;
    private javax.swing.JTable jTableTest2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaInfoPc1;
    private javax.swing.JTextArea jTextAreaInfoPc2;
    private javax.swing.JTextPane jTextPaneCostPerFrame1;
    private javax.swing.JTextPane jTextPaneCostPerFrame2;
    private javax.swing.JTextPane jTextPaneGlogalFps1;
    private javax.swing.JTextPane jTextPaneGlogalFps2;
    private javax.swing.JLabel warIcon3;
    private javax.swing.JLabel warIcon4;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Images/logo.png")));
    }
}
